### ISSUE TITLE
Add config to disable firstline matching lastline regex

### ISSUE THREAD

**Issue by naerymdan** [okkez/fluent-plugin-concat#19]
I'm trying to concatenate java logs and the only way to know to stop matching is to get a 'normal' line again, which also happens to match exactly a first line.

My best scenario would be to start accumulating lines when matching the multiline_start_regexp and end excluding the multiline_end_regexp.

Idea?

My current config:

```
<filter docker.**>
  @type concat
  key log
  multiline_start_regexp /^\d{4}-\d{1,2}-\d{1,2} \d{2}:\d{2}:\d{2}.\d{1,3}/
  multiline_end_regexp /^\d{4}-\d{1,2}-\d{1,2} \d{2}:\d{2}:\d{2}.\d{1,3}/
  stream_identity_key container_id
  use_first_timestamp true
  flush_interval 1s
</filter>
```

example log (simplified, actual log is from docker fluentd logger):

```
2016-09-07 13:17:40.848  WARN 23 --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : There was a problem with the instance info replicator

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
     at com.netflix.discovery.shared.execute(RetryableEurekaHttpClient.java:111) ~[eureka-client-1.4.10.jar:1.4.10]
     at com.netflix.discovery.shared.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.4.10.jar:1.4.10]
     at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92-internal]
	 
2016-09-07 13:17:40.726  INFO 23 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_SERVICE-AUTH/c500a64ed52c:service-auth:9000: registering service...
2016-09-07 13:17:40.801  INFO 23 --- [  restartedMain] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2016-09-07 13:17:40.827 ERROR 23 --- [nfoReplicator-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: service-registry
     at com.sun.jersey.client.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar:1.19.1]
     at com.sun.jersey.api.client.handle(GZIPContentEncodingFilter.java:123) ~[jersey-client-1.19.1.jar:1.19.1]
     at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.4.10.jar:1.4.10]
```

**Comment by naerymdan** [comment]
And...... it work by simply NOT using a multiline_end_regexp. Works marvelously too, thanks for this plugin!
