### ISSUE TITLE
Is this the correct way of detecting multiline lines?

### ISSUE THREAD

**Issue by mpas** [okkez/fluent-plugin-concat#3]
Just wanted to make sure if i understand the multiline detection correctly:

Does the config below correctly detect the multilines:
```
<filter *.docker.*>
  @type concat
  key log
  stream_identity_key container_id
  multiline_start_regexp /^\S+/
  flush_interval 1m
</filter>
```
So if a line has non whitespace followed by other stuff then this is related to the previous line?

If i have loglines like:
```
ERROR org.apache.tomcat.jdbc.pool.ConnectionPool - Unable to create initial connections of pool.
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:249)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:127)
Caused by: java.net.UnknownHostException: dummy-db
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 1 more
```

**Comment by okkez** [comment]
```
multiline_start_regexp /^\S+/
```

```
1  ERROR org.apache.tomcat.jdbc.pool.ConnectionPool - Unable to create initial connections of pool.
2  org.postgresql.util.PSQLException: The connection attempt failed.
3      at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:249)
4      at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
5      at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:127)
6  Caused by: java.net.UnknownHostException: dummy-db
7      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
8      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
9      at java.net.Socket.connect(Socket.java:589)
10 Caused by: java.lang.reflect.InvocationTargetException
11     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14     at java.lang.reflect.Method.invoke(Method.java:497)
15     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
16     ... 1 more
```

* line 1: matched `multiline_start_regexp`
* line 2: matched `multiline_start_regexp` and flush buffer including line 1
* line 3 - line 5: continuation lines, append buffer
* line 6: matched `multiline_start_regexp`, and flush buffer including line 2 - line 5
* line 7 - line 9: continuation lines, append buffer
* line 10: matched `multiline_start_regexp` and flush buffer including line 6 - line 9
* line 11- line 16: continuation lines, append buffer

This is current configuration behavior.

> So if a line has non whitespace followed by other stuff then this is related to the previous line?

You can use `multiline_end_regexp`.
For example:

```
multiline_start_regexp /^ERROR/
multiline_end_regexp /\s+.*more$/
```

This configuration creates event that includes line 1 - line 16 (all lines).
But I don't test this configuration.
